name: Dynamics Solution - Build.yml 
# Export solution from DEV environment
#  unpack it and prepare, commit and push changes to main

on:
  workflow_dispatch:
    inputs:
      solution_name:
        type: choice
        description: The solution to deploy
        required: true
        options:
        - GitHubDeploymentTest
        - Example2ndSolution

env:
#edit your values here
  ENVIRONMENT_URL: 'https://oacdev.crm4.dynamics.com'
  CLIENT_ID: '2b7c51cb-bc68-431c-91f9-23aeaa87f33e'
  TENANT_ID: 'a4cde2db-601c-4294-892c-9b9999462096'
  ROOT_DIR: 'WCC.Dynamics.Solutions'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Who Am I Connection Test
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Get Current Date
      id: currentDate
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYYMMDD"

    #TODO - can't currently see how to avoid re-installing CLI tools
    - name: Update Solution Version
      shell: pwsh
      run: |
        dotnet tool install --global Microsoft.PowerApps.CLI.Tool
        pac auth create --url ${{env.ENVIRONMENT_URL}} --name ${{ github.event.inputs.solution_name }} --applicationId ${{env.CLIENT_ID}} --clientSecret ${{ secrets.PowerPlatformSPN }} --tenant ${{env.TENANT_ID}}
        pac auth select --index 1
        pac solution online-version -sn ${{ github.event.inputs.solution_name }} -sv 1.0.${{ steps.currentDate.outputs.time }}.${{ github.run_number }}

    - name: Publish Solution
      shell: pwsh
      run: |
        pac solution publish
        
    - name: Export Solution As Unmanaged
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{env.ROOT_DIR}}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        managed: false
        overwrite: true

    - name: Export Solution As Managed
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{env.ROOT_DIR}}/${{ github.event.inputs.solution_name }}_managed.zip
        managed: true
        overwrite: true

    - name: Unpack Unmanaged Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{env.ROOT_DIR}}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        solution-folder: ${{env.ROOT_DIR}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Commit Changes to Repo 
      run: |
        git fetch --all  
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
