name: Dynamics Solution - Deploy.yml 
# Deploy managed solution file from source control

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to include in the release'
        required: true
        default: GitHubDeploymentTest
      activate_plugins:
        description: 'Should the release auto-active any plugins or workflow steps contained in the solution'
        required: false
        default: true

env:
#edit your values here
  ENVIRONMENT_URL: 'https://oac.crm4.dynamics.com/'
  CLIENT_ID: '2b7c51cb-bc68-431c-91f9-23aeaa87f33e'
  TENANT_ID: 'a4cde2db-601c-4294-892c-9b9999462096'
  ROOT_DIR: 'WCC.Dynamics.Solutions'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Who Am I Connection Test
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{env.ROOT_DIR}}/${{ github.event.inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true
