name: dynamics-solution-export.yml 
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: GitHubDeploymentTest
       #Do Not change these values
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: WCC.Dynamics.Solutions/

env:
#edit your values here
  ENVIRONMENT_URL: 'https://oacdev.crm4.dynamics.com'
  CLIENT_ID: '2b7c51cb-bc68-431c-91f9-23aeaa87f33e'
  TENANT_ID: 'a4cde2db-601c-4294-892c-9b9999462096'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    

    #TODO - can't currently see how to avoid re-installing CLI tools
    - name: Update Solution Version
      shell: pwsh
      run: |
        dotnet tool install --global Microsoft.PowerApps.CLI.Tool
        pac auth create --url ${{env.ENVIRONMENT_URL}} --name ${{ github.event.inputs.solution_name }} --applicationId ${{env.CLIENT_ID}} --clientSecret ${{ secrets.PowerPlatformSPN }} --tenant ${{env.TENANT_ID}}
        pac auth select --index 1
        pac solution online-version -sn ${{ github.event.inputs.solution_name }} -sv 1.0.${{ github.run_id }}.${{ github.run_number }}

    - name: Update Solution Version
      shell: pwsh
      run: |
        pac solution publish
        
    - name: Export Solution As Unmanaged
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        managed: false

    - name: Export Solution As Managed
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        managed: true

    - name: Unpack Unmanaged Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Commit Changes to Repo 
      run: |
        git fetch --all  
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
