name: versiontest
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: ProPCF
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
       
env:
#edit your values here
  ENVIRONMENT_URL: 'https://oacdev.crm4.dynamics.com'
  CLIENT_ID: '2b7c51cb-bc68-431c-91f9-23aeaa87f33e'
  TENANT_ID: 'a4cde2db-601c-4294-892c-9b9999462096'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    
    - run: |
        dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - run: |
        pac auth create --url ${{env.ENVIRONMENT_URL}} --name ${{ github.event.inputs.solution_name }} --applicationId ${{env.CLIENT_ID}} --clientSecret ${{ secrets.PowerPlatformSPN }} --tenant ${{env.TENANT_ID}}

    - run: |
        pac auth select --index 1

    - name: update solution version
      run: >
        pac solution online-version
        -sn ${{ github.event.inputs.solution_name }}
        -sv 1.0.0.${{ github.run_number }}
